export enum EndPoint {
  AUTH = "auth",
  ORDERS = "orders",
  COURIERS = "courier",
  SHIPMENTS = "shipments",
  RETURNS = "returns",
  TRACKING = "shipments/track",
  LABELS = "shipments/print",
  PICKUPS = "settings/company/pickup",
  PRODUCTS = "products",
  INVENTORY = "inventory",
  ACCOUNT = "account",
  NDR = "ndr",
  CHANNELS = "channels",
  LISTINGS = "listings",
  COUNTRIES = "geopoint",
  STATEMENTS = "statement",
  DISCREPANCIES = "discrepancy",
  FILES = "file",
  WRAPPER = "wrapper",
  HYPERLOCAL = "hyperlocal",
  INTERNATIONAL = "international",
}
